Repository ocp-power-automation/infra, pull requests merged in 2020-09, with the labels that each got.

#8 Update convert_qcow2_ova.py
  scripts/images/convert_qcow2_ova.py
Labels: size/XS

#9 Bind mounting machine-id
  scripts/images/convert_qcow2_ova.py
Labels: lgtm, size/XS

#10 Add resolv.conf for temp purpose
  scripts/images/convert_qcow2_ova.py
Labels: lgtm, size/XS

#11 Fix the script
  scripts/images/convert_qcow2_ova.py
Labels: size/XS

#12 Fixes
  scripts/images/README.md
  scripts/images/convert_qcow2_ova.py
Labels: size/S

#13 Implement boto3 flow for non amd archs
  scripts/images/upload_image.py
Labels: lgtm, size/L

#14 Add timeout, dracut fix and print cmd
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/XS

#15 Include rmc fix and use pigz
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/M

#16 Update documentation for the image related scripts
  scripts/images/README.md
Labels: approved, lgtm, size/L

#17 README updates with missing details for OVA process
  scripts/images/README.md
Labels: approved, lgtm, size/XS
