Repository ocp-power-automation/infra, pull requests merged in 2020-10, with the labels that each got.

#18 Add a set of scripts to collect data from PowerVS
  scripts/powervs-data-collector/README.md
  scripts/powervs-data-collector/collect.sh
  scripts/powervs-data-collector/main.tf
  scripts/powervs-data-collector/provider.tf
  scripts/powervs-data-collector/runner.sh
  scripts/powervs-data-collector/variables.tf
Labels: approved, lgtm, size/L

#19 Update PowerVS image upload/import README
  scripts/images/README.md
Labels: approved, size/S

#21 Add link to CoreOS Qcow2
  scripts/images/README.md
  scripts/images/create_boot_images.py
  scripts/images/upload_image.py
Labels: approved, size/S

#23 Add multipath support
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/S

#22 Enhance the readability
  scripts/images/README.md
Labels: approved, lgtm, size/M

#25 Update OVA generation code
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/L

#26 Fix imagesize var handling and set default image size to 120
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/XS

#27 Resize the rootfs while building the image
  scripts/images/README.md
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/S

#28 Fix the review comments for the PR-27
  scripts/images/convert_qcow2_ova.py
Labels: approved, lgtm, size/S
